### ISSUE TITLE
Ability to save the report or results from report

### ISSUE THREAD

**Issue by rebecca-smith** [wearefriday/gherkin-test-report#2]
It would be great addition if the report could be saved and reopened to work on or if the results could be saved and auto-filled in the report. 

Most test results will be the same one day to the next with a 1 or 2 changing, being able to open the report from the day before or a way to automatically fill in the results using another report would be good!

:)

**Comment by nickdunn** [comment]
> It would be great addition if the report could be saved and reopened to work on 

This is already possible. Once you're finished working on the report, click the "Save HTML" button at the top. This will make your browser download a new version of the HTML file that is a replica of the one you're working on. You can open this file up and continue working. Click "Save HTML" again when you're finished to get a new file, and discard the old one.

> Most test results will be the same one day to the next with a 1 or 2 changing, being able to open the report from the day before or a way to automatically fill in the results using another report would be good!

This is a really good point. While you can open up an old report and create a duplicate from it, this is only useful if the scenarios are exactly the same each time. If you've added new feature files, or if the scenarios themselves have changed, you'd have to re-run the ruby script to generate an entirely new blank report. It'd be really nice if you could use the results from a previous HTML file to fill in the results when creating a new one with the script — just like you can pass in the results from a Cucumber test run...

**Comment by nickdunn** [comment]
https://github.com/wearefriday/gherkin-test-report/pull/7
